PERI.Prompt.Web/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PERI.Prompt.BLL;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PERI.Prompt.Web.Controllers
{
    public class PageController : BLL.BaseTemplateController
    {
        private readonly IUnitOfWork unitOfWork;

        public PageController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index(string permalink)
        {
            var context = new EF.SampleDbContext();

            var rec = await new BLL.Page(unitOfWork).Get(new EF.Page { Permalink = permalink });

            if (rec != null)
            {
                ViewData["Title"] = rec.Title;
                return View(rec);
            }
            else
                return StatusCode(404);
        }
    }
}

PERI.Prompt.Web/Areas/Admin/Views/Page/Edit.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@model Tuple<EF.Page, bool>
@{

    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

<style>
    .crop {
        width: 200px;
        height: 150px;
        overflow: hidden;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit page
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Page", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(x => x.Item1.PageId)
                            <div class="form-group">
                                <label>Title *</label>
                                @Html.TextBoxFor(x => x.Item1.Title, new { @class = "form-control", placeholder = "Title", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Permalink *</label>
                                @Html.TextBoxFor(x => x.Item1.Permalink, new { @class = "form-control", placeholder = "Permalink", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Content *</label>
                                <div>
                                    @Html.TextAreaFor(x => x.Item1.Content, new { @class = "textarea", placeholder = "Body", style = "width: 100%; height: 350px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Photo</label>

                                @if (Model.Item1.PagePhoto.Count() > 0)
                                {
                                    <div class="crop">
                                        <img src="@string.Concat(this.Context.Request.Scheme, "://", this.Context.Request.Host, "/", Model.Item1.PagePhoto.First().Photo.Url)" style="max-width:100%; max-height:250px" />
                                    </div>
                                }

                                <input type="file" name="file" accept="image/*" />
                                <p class="help-block">Leave it blanked if you don't need to update the photo.</p>
                            </div>

                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(x => x.Item2)
                                    Is active
                                </label>
                            </div>

                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a href="#" class="btn btn-default" onclick="window.history.back();">Cancel</a>
                        }
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<!-- Bootstrap WYSIHTML5 -->
<script src="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

PERI.Prompt.Web/Areas/Admin/Views/Page/Index.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@using BLL = PERI.Prompt.BLL
@model EF.Page
@{
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Search pages
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12" id="main">
                        @using (Html.BeginForm())
                        {
                            @Html.HiddenFor(x => x.CreatedBy)
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label>Title</label>
                                @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Search" })
                            </div>

                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-default" id="clear">Clear</button>
                        }
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Pages
            </div>

            <!-- /.panel-heading -->
            <div class="panel-body" style="overflow: auto">
                <a href="~/Admin/Page/New" class="btn btn-primary">New</a>
                <a href="#" class="btn btn-default" id="delete">Delete</a>
                <a href="#" class="btn btn-default" id="activate">Activate</a>
                <a href="#" class="btn btn-default" id="deactivate">Deactivate</a>
                <br />
                <br />
                <table width="100%" class="table table-striped table-bordered table-hover" id="tbl">
                    <thead>
                        <tr>
                            <th class="head0" style="text-align: center; width: 5%"><input type="checkbox" id="checkall" /></th>
                            <th class="head0" style="text-align: center; width: 5%"></th>
                            <th>Title</th>
                            <th>Permalink</th>
                            <th>Author</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var rec in (ViewBag.Data as IEnumerable<EF.Page>))
                        {
                            <tr class="odd gradeX">
                                <td><input type="checkbox" class="checkBox" value="@rec.PageId" /></td>
                                <td>

                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                            Action
                                            <span class="fa fa-caret-down"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="~/Admin/Page/Edit/@rec.PageId">Edit</a></li>
                                        </ul>
                                    </div>

                                </td>
                                <td>@rec.Title</td>
                                <td>@rec.Permalink</td>
                                <td>@rec.CreatedBy</td>
                                <td>@(rec.DateInactive == null)</td>
                            </tr>
                        }

                    </tbody>
                </table>

                <br />
                <br />
                <br />
                <br />
                <br />
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<script>
    $(document).ready(function () {
        $("#tbl").DataTable({
            "bFilter": false,
            "sPaginationType": "full_numbers",
            "order": [],
            "columnDefs": [{
                "targets": [0, 1, 2],
                "orderable": false
            }]
        });

        $("#clear").click(function () {
            $('#main').children().each(function () {
                $(this).find("input[type=text], textarea").val("");
                $(this).find("input[type=password]").val("");
                $(this).find("input[type=email]").val("");
                $(this).find('select').each(function () {
                    $(this).find('option:first').prop('selected', 'selected');
                });
            });
            return false;
        });

        $("#delete").click(function () {
            var flag = confirm('Are you sure you want to delete selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/admin/page/delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });

        $("#activate").click(function () {
            var flag = confirm('Are you sure you want to activate selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/admin/page/activate";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while activating the records!");
            };
            $.ajax(options);

        });

        $("#deactivate").click(function () {
            var flag = confirm('Are you sure you want to deactivate selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/admin/page/deactivate";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deactivating the users!");
            };
            $.ajax(options);

        });

        $("#checkall").change(function () {
            /*$("input:checkbox").prop('checked', $(this).prop("checked"));*/
            var chk = $(this).prop("checked");
            $("#tbl").find('input[type=checkbox]').each(function () {
                this.checked = chk;
            });
        });
    });
</script>

PERI.Prompt.Web/Areas/Admin/Views/Page/New.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@model Tuple<EF.Page, bool>
@{
    
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New page
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("New", "Page", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label>Title *</label>
                                @Html.TextBoxFor(x => x.Item1.Title, new { @class = "form-control", placeholder = "Title", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Permalink *</label>
                                @Html.TextBoxFor(x => x.Item1.Permalink, new { @class = "form-control", placeholder = "Permalink", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Content *</label>
                                <div>
                                    @Html.TextAreaFor(x => x.Item1.Content, new { @class = "textarea", placeholder = "Content", required = "", style = "width: 100%; height: 350px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Photo</label>
                                <input type="file" name="file" accept="image/*" />
                            </div>

                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(x => x.Item2)
                                    Is active
                                </label>
                            </div>

                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a href="#" class="btn btn-default" onclick="window.history.back();">Cancel</a>
                        }
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<!-- Bootstrap WYSIHTML5 -->
<script src="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>