PERI.Prompt.Web/Areas/Admin/Controllers/ChildMenuItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using PERI.Prompt.BLL;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PERI.Prompt.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class ChildMenuItemController : BLL.BaseController
    {
        private readonly IUnitOfWork unitOfWork;

        public ChildMenuItemController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: /<controller>/
        [Route("Menu/{id:int}/Items/{id1:int}/Children")]
        public async Task<IActionResult> Index(int id, int id1)
        {
            var menuitem = await new BLL.MenuItem(unitOfWork).Get(new EF.MenuItem { MenuItemId = id1 });

            ViewData["Title"] = "Menu/" + menuitem.Menu.Name + "/" + menuitem.Label;

            var tuple = new Tuple<EF.ChildMenuItem, List<EF.ChildMenuItem>>(new EF.ChildMenuItem { MenuItem = menuitem, MenuItemId = id1 }, menuitem.ChildMenuItem.ToList());

            return View(tuple);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Menu/{id:int}/Items/{id1:int}/Children/New")]
        public async Task<IActionResult> New([Bind(Prefix = "Item1")] EF.ChildMenuItem args, int id, int id1)
        {
            try
            {
                await new BLL.ChildMenuItem(unitOfWork).Add(args);
            }
            catch (DbUpdateException ex)
            {
                TempData["notice"] = "Entry is causing conflict or already exist.";
            }

            return RedirectToAction("Index", new { id = id, id1 = id1 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Menu/{id:int}/Items/{id1:int}/Children/Save")]
        public async Task<IActionResult> Save([Bind(Prefix = "Item2")] List<EF.ChildMenuItem> args, int id, int id1)
        {
            try
            {
                foreach (var rec in args)
                    await new BLL.ChildMenuItem(unitOfWork).Edit(rec);
            }
            catch (DbUpdateException ex)
            {
                TempData["notice"] = "Entry is causing conflict or already exist.";
            }

            return RedirectToAction("Index", new { id = id, id1 = id1 });
        }

        [HttpPost]
        [Route("Menu/{id:int}/Items/{id1:int}/Children/Delete")]
        public async Task<IActionResult> Delete([FromBody] int[] ids)
        {
            await new BLL.ChildMenuItem(unitOfWork).Delete(ids);

            return Json("Success!");
        }
    }
}

PERI.Prompt.Web/Areas/Admin/Views/ChildMenuItem/Index.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@using BLL = PERI.Prompt.BLL
@model Tuple<EF.ChildMenuItem, List<EF.ChildMenuItem>>
@{
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New child menu item: @Model.Item1.MenuItem.Label
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12" id="main">
                        @using (Html.BeginForm("New", "ChildMenuItem"))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(x => x.Item1.MenuItemId)
                            <div class="form-group">
                                <label>Label</label>
                                @Html.TextBoxFor(x => x.Item1.Label, new { @class = "form-control", @placeholder = "Label", @required = "" })
                            </div>

                            <div class="form-group">
                                <label>URL</label>
                                @Html.TextBoxFor(x => x.Item1.Url, new { @class = "form-control", @placeholder = "URL", @required = "" })
                            </div>

                            <div class="form-group">
                                <label>Order</label>
                                @Html.TextBoxFor(x => x.Item1.Order, new { @class = "form-control", @placeholder = "Order", @required = "", @type = "number" })
                            </div>

                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Add</button>
                            <button type="reset" class="btn btn-default" id="clear">Clear</button>
                        }
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Child menu items: @Model.Item1.MenuItem.Label
            </div>

            @using (Html.BeginForm("Save", "ChildMenuItem"))
            {
            <!-- /.panel-heading -->
                <div class="panel-body" style="overflow: auto">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="#" class="btn btn-default" id="delete">Delete</a>
                    <br />
                    <br />
                    <table width="100%" class="table table-striped table-bordered table-hover" id="tbl">
                        <thead>
                            <tr>
                                <th class="head0" style="text-align: center; width: 5%"><input type="checkbox" id="checkall" /></th>
                                
                                <th>Label</th>
                                <th>URL</th>
                                <th>Order</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (var cnt = 0; cnt < Model.Item2.Count(); cnt++)
                            {
                                <tr class="odd gradeX">
                                    <td><input type="checkbox" class="checkBox" value="@Model.Item2[cnt].ChildMenuItemId" /></td>

                                    
                                    <td>
                                        @Html.HiddenFor(x => x.Item2[cnt].ChildMenuItemId)
                                        @Html.TextBoxFor(x => x.Item2[cnt].Label, new { @class = "form-control", @style = "width:100%" })
                                    </td>
                                    <td>@Html.TextBoxFor(x => x.Item2[cnt].Url, new { @class = "form-control", @style = "width:100%" })</td>
                                    <td>@Html.TextBoxFor(x => x.Item2[cnt].Order, new { @class = "form-control", @style = "width:100%" })</td>
                                    
                                </tr>
                            }
                        </tbody>
                    </table>

                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <!-- /.table-responsive -->

                </div>
            <!-- /.panel-body -->
            }
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<script>
    $(document).ready(function () {
        $("#tbl").DataTable({
            "bFilter": false,
            "sPaginationType": "full_numbers",
            "order": [],
            "columnDefs": [{
                "targets": [0, 1],
                "orderable": false
            }]
        });

        $("#clear").click(function () {
            $('#main').children().each(function () {
                $(this).find("input[type=text], textarea").val("");
                $(this).find("input[type=password]").val("");
                $(this).find("input[type=email]").val("");
                $(this).find('select').each(function () {
                    $(this).find('option:first').prop('selected', 'selected');
                });
            });
            return false;
        });

        $("#delete").click(function () {
            var flag = confirm('Are you sure you want to delete selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/menu/@Model.Item1.MenuItem.MenuId/items/@Model.Item1.MenuItemId/children/delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });

        $("#checkall").change(function () {
            /*$("input:checkbox").prop('checked', $(this).prop("checked"));*/
            var chk = $(this).prop("checked");
            $("#tbl").find('input[type=checkbox]').each(function () {
                this.checked = chk;
            });
        });
    });
</script>