PERI.Prompt.Web/Areas/Main/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using PERI.Prompt.BLL;

namespace PERI.Prompt.Web.Areas.Main.Controllers
{
    [Area("Main")]
    [Authorize(Roles = "Admin,Blogger")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class EventController : BLL.BaseController
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IHostingEnvironment _environment;
        public EventController(IHostingEnvironment environment, IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "Events";

            ViewBag.Data = await new BLL.Event(unitOfWork).Find(new EF.Event());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(EF.Event args)
        {
            ViewData["Title"] = "Events";
            ViewBag.Data = await new BLL.Event(unitOfWork).Find(args);
            return View();
        }

        public IActionResult New()
        {
            ViewData["Title"] = "Event/New";
            
            return View(new Tuple<EF.Event, bool>(new EF.Event { Time = DateTime.Now }, true));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New([Bind(Prefix = "Item1")] EF.Event model, [Bind(Prefix = "Item2")] bool isactive, IFormFile file)
        {
            ViewData["Title"] = "Event/New";

            model.CreatedBy = User.Identity.Name;

            var bevent = new BLL.Event(unitOfWork);

            // Add Event
            if (!isactive)
                model.DateInactive = DateTime.Now;
            else
                model.DateInactive = null;

            var id = await bevent.Add(model);

            // Add Photo
            IFormFile uploadedImage = file;
            if (uploadedImage != null && uploadedImage.ContentType.ToLower().StartsWith("image/"))
            {
                var pid = await new BLL.Photo(unitOfWork).Add(_environment, file);

                var ep = new EF.EventPhoto();
                ep.EventId = id;
                ep.PhotoId = pid;
                await new BLL.EventPhoto(unitOfWork).Add(ep);
            }

            return Redirect("~/Main/Event");
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Event/Edit";

            var obj = await (new BLL.Event(unitOfWork).GetModel(id));
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind(Prefix = "Item1")] EF.Event model, [Bind(Prefix = "Item2")] bool isactive, IFormFile file)
        {
            ViewData["Title"] = "Event/Edit";

            model.ModifiedBy = User.Identity.Name;

            var bevent = new BLL.Event(unitOfWork);

            // Update Event
            if (!isactive)
                model.DateInactive = DateTime.Now;
            else
                model.DateInactive = null;

            await bevent.Edit(model);

            // Update Photo
            IFormFile uploadedImage = file;
            if (uploadedImage != null && uploadedImage.ContentType.ToLower().StartsWith("image/"))
            {
                var beventphoto = new BLL.EventPhoto(unitOfWork);
                var eventphotos = await beventphoto.Find(new EF.EventPhoto { EventId = model.EventId });
                if (eventphotos.Count() > 0)
                    await new BLL.Photo(unitOfWork).Delete(eventphotos.First().PhotoId, _environment);

                var pid = await new BLL.Photo(unitOfWork).Add(_environment, file);

                var ep = new EF.EventPhoto();
                ep.EventId = model.EventId;
                ep.PhotoId = pid;
                await beventphoto.Edit(ep);
            }

            return Redirect("~/Main/Event");
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] int[] ids)
        {
            var bevent = new BLL.Event(unitOfWork);

            // Delete photos
            var eventphotos = await new BLL.EventPhoto(unitOfWork).Get(ids);
            if (eventphotos.Count() > 0)
                await new BLL.Photo(unitOfWork).Delete(eventphotos.Select(x => x.PhotoId).ToArray(), _environment);

            await bevent.Delete(ids);

            return Json("Success!");
        }

        [HttpPost]
        public async Task<IActionResult> Activate([FromBody] int[] ids)
        {
            var bevent = new BLL.Event(unitOfWork);

            await bevent.Activate(ids);

            return Json("Success!");
        }

        [HttpPost]
        public async Task<IActionResult> Deactivate([FromBody] int[] ids)
        {
            var bevent = new BLL.Event(unitOfWork);

            await bevent.Deactivate(ids);

            return Json("Success!");
        }
    }
}

PERI.Prompt.Web/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PERI.Prompt.BLL;

namespace PERI.Prompt.Web.Controllers
{
    public class EventController : BLL.BaseTemplateController
    {
        private readonly IUnitOfWork unitOfWork;

        public EventController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> View(int id)
        {
            var rec = await new BLL.Event(unitOfWork).Get(new EF.Event { EventId = id });

            ViewData["Title"] = rec.Name;

            return View(rec);
        }
    }
}

PERI.Prompt.Web/Areas/Main/Views/Event/Edit.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@model Tuple<EF.Event, bool>
@{
    ViewData["Title"] = "Event/New";
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<script type="text/javascript" src="~/template/admin/datetimepicker/js/moment.js"></script>
<script type="text/javascript" src="~/template/admin/datetimepicker/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" href="~/template/admin/datetimepicker/css/bootstrap-datetimepicker.css" />

<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

<style>
    .crop {
        width: 200px;
        height: 150px;
        overflow: hidden;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New event
            </div>
            <div class="panel-body">
                <div class="row">
                    @using (Html.BeginForm("Edit", "Event", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(x => x.Item1.EventId)
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name *</label>
                                @Html.TextBoxFor(x => x.Item1.Name, new { @class = "form-control", placeholder = "Name", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Description *</label>
                                <div>
                                    @Html.TextAreaFor(x => x.Item1.Description, new { @class = "textarea", placeholder = "Description", required = "", style = "width: 100%; height: 350px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" })
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Location *</label>
                                @Html.TextBoxFor(x => x.Item1.Location, new { @class = "form-control", placeholder = "Location", required = "", maxlength = "200" })
                            </div>

                            <div class="form-group">
                                <label>Time *</label>
                                <div>
                                    @Html.TextBoxFor(x => x.Item1.Time, new { @class = "form-control", placeholder = "Time", required = "" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Photo</label>

                                @if (Model.Item1.EventPhoto.Count() > 0)
                                {
                                    <div class="crop">
                                        <img src="@string.Concat(this.Context.Request.Scheme, "://", this.Context.Request.Host, "/", Model.Item1.EventPhoto.First().Photo.Url)" style="max-width:100%; max-height:250px" />
                                    </div>
                                }

                                <input type="file" name="file" accept="image/*" />
                                <p class="help-block">Leave file-upload blanked if you don't need to update the photo.</p>
                            </div>

                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(x => x.Item2)
                                    Is active
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-12  text-right">
                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a href="#" class="btn btn-default" onclick="window.history.back();">Cancel</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap WYSIHTML5 -->
<script src="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<script>
    $(document).ready(function () {
        $(function () {
            $('#Item1_Time').datetimepicker();
        });
    });
</script>

PERI.Prompt.Web/Areas/Main/Views/Event/Index.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@using BLL = PERI.Prompt.BLL
@model EF.Event
@{
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Search events
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12" id="main">
                        @using (Html.BeginForm())
                        {
                            @Html.HiddenFor(x => x.CreatedBy)
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label>Name</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Name" })
                            </div>

                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-default" id="clear">Clear</button>
                        }
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    <!-- /.col-lg-6 (nested) -->
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Events
            </div>

            <!-- /.panel-heading -->
            <div class="panel-body" style="overflow: auto">
                <a href="~/Main/Event/New" class="btn btn-primary">New</a>
                <a href="#" class="btn btn-default" id="delete">Delete</a>
                <a href="#" class="btn btn-default" id="activate">Activate</a>
                <a href="#" class="btn btn-default" id="deactivate">Deactivate</a>
                <br />
                <br />
                <table width="100%" class="table table-striped table-bordered table-hover" id="tbl">
                    <thead>
                        <tr>
                            <th class="head0" style="text-align: center; width: 5%"><input type="checkbox" id="checkall" /></th>
                            <th class="head0" style="text-align: center; width: 5%"></th>
                            <th>Name</th>
                            <th>Time</th>
                            <th>Location</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var rec in (ViewBag.Data as IEnumerable<EF.Event>))
                        {
                            <tr class="odd gradeX">
                                <td><input type="checkbox" class="checkBox" value="@rec.EventId" /></td>
                                <td>

                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                            Action
                                            <span class="fa fa-caret-down"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="~/Main/Event/Edit/@rec.EventId">Edit</a></li>
                                        </ul>
                                    </div>

                                </td>
                                <td>@rec.Name</td>
                                <td>@rec.Time</td>
                                <td>@rec.Location</td>
                                <td>@(rec.DateInactive == null)</td>
                            </tr>
                        }

                    </tbody>
                </table>

                <br />
                <br />
                <br />
                <br />
                <br />
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<script>
    $(document).ready(function () {
        $("#tbl").DataTable({
            "bFilter": false,
            "sPaginationType": "full_numbers",
            "order": [],
            "columnDefs": [{
                "targets": [0, 1, 2],
                "orderable": false
            }]
        });

        $("#clear").click(function () {
            $('#main').children().each(function () {
                $(this).find("input[type=text], textarea").val("");
                $(this).find("input[type=password]").val("");
                $(this).find("input[type=email]").val("");
                $(this).find('select').each(function () {
                    $(this).find('option:first').prop('selected', 'selected');
                });
            });
            return false;
        });

        $("#delete").click(function () {
            var flag = confirm('Are you sure you want to delete selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/main/event/delete";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });

        $("#activate").click(function () {
            var flag = confirm('Are you sure you want to activate selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/main/event/activate";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while activating the records!");
            };
            $.ajax(options);

        });

        $("#deactivate").click(function () {
            var flag = confirm('Are you sure you want to deactivate selected records?');

            if (!flag)
                return false;

            var selectedIDs = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    selectedIDs.push($(this).val());
                }
            });

            var options = {};
            options.url = "/main/event/deactivate";
            options.type = "POST";
            options.data = JSON.stringify(selectedIDs);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deactivating the users!");
            };
            $.ajax(options);

        });

        $("#checkall").change(function () {
            /*$("input:checkbox").prop('checked', $(this).prop("checked"));*/
            var chk = $(this).prop("checked");
            $("#tbl").find('input[type=checkbox]').each(function () {
                this.checked = chk;
            });
        });
    });
</script>

PERI.Prompt.Web/Areas/Main/Views/Event/New.cshtml
@using EF = PERI.Prompt.EF
@using Core = PERI.Prompt.Core
@model Tuple<EF.Event, bool>
@{
    ViewData["Title"] = "Event/New";
    Layout = "~/Views/Shared/Blogger/Main.cshtml";
}

<script type="text/javascript" src="~/template/admin/datetimepicker/js/moment.js"></script>
<script type="text/javascript" src="~/template/admin/datetimepicker/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" href="~/template/admin/datetimepicker/css/bootstrap-datetimepicker.css" />

<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New event
            </div>
            <div class="panel-body">
                <div class="row">
                    @using (Html.BeginForm("New", "Event", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name *</label>
                                @Html.TextBoxFor(x => x.Item1.Name, new { @class = "form-control", placeholder = "Name", required = "", maxlength = "50" })
                            </div>

                            <div class="form-group">
                                <label>Description *</label>
                                <div>
                                    @Html.TextAreaFor(x => x.Item1.Description, new { @class = "textarea", placeholder = "Description", required = "", style = "width: 100%; height: 350px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" })
                                </div>
                            </div>                            
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Location *</label>
                                @Html.TextBoxFor(x => x.Item1.Location, new { @class = "form-control", placeholder = "Location", required = "", maxlength = "200" })
                            </div>

                            <div class="form-group">
                                <label>Time *</label>
                                <div>
                                    @Html.TextBoxFor(x => x.Item1.Time, new { @class = "form-control", placeholder = "Time", required = "" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Photo</label>
                                <input type="file" name="file" accept="image/*" />
                            </div>

                            <div class="checkbox">
                                <label>
                                    @Html.CheckBoxFor(x => x.Item2)
                                    Is active
                                </label>
                            </div>
                        </div>

                        <div class="col-lg-12 text-right">
                            <span style="color:red">@Html.ValidationSummary()</span>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a href="#" class="btn btn-default" onclick="window.history.back();">Cancel</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap WYSIHTML5 -->
<script src="~/template/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<script>
    $(document).ready(function () {
        $(function () {
            $('#Item1_Time').datetimepicker();
        });
    });
</script>